spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/spring-cloud-366?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    host: jtik.sunnywit.top
    port: 5672
    username: ori
    password: 424487386
  cloud:
    stream:
      myMessage:
        group: order
